### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by vixe76** [DMKEBUSINESSGMBH/typo3-t3socials#1]
Hi, first of all it's not really an issue more a feature request! Any plans to refactor your extension with pure extbase? Your extension sounds very cool but the dependency on rn_base scares me from.

Best Regards
Falk

**Comment by hannesbochmann** [comment]
Nope, this will not happen as we develop rn_base ourself. You don't need to be scared from ;-)

**Comment by vixe76** [comment]
Thx for your fast reply ... then I will take a closer look at rn_base.
