### ISSUE TITLE
Declaration of tx_t3socials_models_NetworkConfig::init($rowOrUid) should be compatible with tx_rnbase_model_base::init($rowOrUid = NULL)

### ISSUE THREAD

**Issue by FreddyFFM** [DMKEBUSINESSGMBH/typo3-t3socials#7]
Hi there,

after installing t3socials with rn_base I always get the following error, regardless of the t3socials version (starting 2.0.0) or the rn_base version (starting 1.0.9).
With this error no other backend option nor the frontend is available.

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1: PHP Warning: Declaration of tx_t3socials_models_NetworkConfig::init($rowOrUid) should be compatible with tx_rnbase_model_base::init($rowOrUid = NULL) in /www/htdocs/w010b0ae/mtv_typo3_dev/typo3conf/ext/t3socials/models/class.tx_t3socials_models_NetworkConfig.php line 37 | TYPO3\CMS\Core\Error\Exception thrown in file /www/htdocs/w010b0ae/mtv_typo3_dev/typo3_src-7.6.18/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 111. Requested URL: https://mtvdev.xxx/typo3/index.php?M=tools_ExtensionmanagerExtensionmanager&moduleToken=7ee1b817b91a38e846ae834fff7595e3b685d9c1&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bextension%5D=38435&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=installExtensionWithoutSystemDependencyCheck&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=Download&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bformat%5D=json

PHP Version is 7.0.14
Typo3 Version is 7.6.18

I assume it may be a problem with the PHP Version?

**Comment by hannesbochmann** [comment]
This was no problem with the PHP version. The problem occured due to changes of rn_base. Everything should now work as expected.

**Comment by FreddyFFM** [comment]
Thanks for solving that issue: After adding a twitter-App I try to login to twitter and get the popup-message.

> No backend function registered for ajaxID "t3socials-hybridauth".

Config is BE->AJAX->t3socials-hybridauth = /mypathto typo3/typo3conf/ext/t3socials/network/hybridauth/class.tx_t3socials_network_hybridauth_OAuthCall.php:tx_t3socials_network_hybridauth_OAuthCall->ajaxId

Did I missed something or is an issue?

**Comment by hannesbochmann** [comment]
I don't have time to test this but the following should work. Replace the lines 40-42 in ext_localconf.php with the following code:
```
tx_rnbase_util_Extensions::registerAjaxHandler (
    't3socials-hybridauth',
    tx_rnbase_util_Extensions::extPath(
        't3socials', 
        'network/hybridauth/class.tx_t3socials_network_hybridauth_OAuthCall.php'
    ) .
    ':tx_t3socials_network_hybridauth_OAuthCall->ajaxId'
);
```

**Comment by FreddyFFM** [comment]
With

tx_rnbase_util_Extensions::registerAjaxHandler (
            't3socials-hybridauth',
            tx_rnbase_util_Extensions::extPath(
                        't3socials',
                  'network/hybridauth/class.tx_t3socials_network_hybridauth_OAuthCall.php'
                        ) .
            ':tx_t3socials_network_hybridauth_OAuthCall->ajaxId',
            false
            );

it worked. Just wondering why I had to set the token to false.

Von: Hannes Bochmann [mailto:notifications@github.com]
Gesendet: Donnerstag, 8. Juni 2017 14:43
An: DMKEBUSINESSGMBH/typo3-t3socials <typo3-t3socials@noreply.github.com>
Cc: Fraedrich, Michael <m.fraedrich@proventa.de>; Comment <comment@noreply.github.com>
Betreff: [SPAM] Re: [DMKEBUSINESSGMBH/typo3-t3socials] Declaration of tx_t3socials_models_NetworkConfig::init($rowOrUid) should be compatible with tx_rnbase_model_base::init($rowOrUid = NULL) (#7)


I don't have time to test this but the following should work. Replace the lines 40-42 in ext_localconf.php with the following code:

tx_rnbase_util_Extensions::registerAjaxHandler (

    't3socials-hybridauth',

    tx_rnbase_util_Extensions::extPath(

        't3socials',

        'network/hybridauth/class.tx_t3socials_network_hybridauth_OAuthCall.php'

    ) .

    ':tx_t3socials_network_hybridauth_OAuthCall->ajaxId'

);
